# Load the Aptok vocabulary/builders Lepos uses without pulling in optional stores.
require "aptok/portable"
require "aptok/vocabulary/vocabulary"
require "aptok/vocabulary/vocabulary_core_entities"
require "aptok/vocabulary/vocabulary_activity_entities"
require "aptok/vocabulary/vocabulary_social_objects"
require "aptok/vocabulary/vocabulary_forgefed_entities"
require "aptok/vocabulary/vocabulary_marketplace_context"
require "aptok/vocabulary/vocabulary_marketplace_entities"
require "aptok/vocabulary/vocabulary_activity_builders"
require "aptok/vocabulary/vocabulary_forgefed_marketplace_builders"
require "aptok/vocabulary/vocabulary_marketplace_collections"
require "aptok/vocabulary/vocabulary_validators"
